apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limiter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rate-limiter
  template:
    metadata:
      labels:
        app: rate-limiter
    spec:
      containers:
        - name: rate-limiter
          image: rate-limiter-service:latest  
          imagePullPolicy: Never              
          ports:
            - containerPort: 3000
